name: zet_health
description: "Zet Health"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.7.0+22

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_svg: ^2.1.0
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.8.0
  intl: ^0.20.2
  http: ^1.4.0
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  flutter_advanced_drawer: ^1.5.0
  dotted_border: ^2.1.0
  flutter_widget_from_html: ^0.16.0
  device_info_plus: ^11.4.0
  package_info_plus: ^8.3.0
  flutter_easyloading: ^3.0.5
#  flutter_swipe_button: ^2.1.1+1
  url_launcher: ^6.3.1
  open_file: ^3.5.10
  share_plus: ^11.0.0
  flutter_pdfview: ^1.3.2
  flutter_markdown: ^0.7.4+1
  lottie: ^3.1.3

  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  file_picker: ^8.1.4
  google_maps_flutter: ^2.12.2
  location: ^8.0.0
  geocoding: ^4.0.0
  flutter_local_notifications: ^19.3.1
  razorpay_flutter: ^1.4.0
  sqflite: ^2.4.2
  path: ^1.9.1

  permission_handler: ^12.0.0+1
  geolocator: ^14.0.1
  store_redirect: ^2.0.4
  flutter_typeahead: ^5.2.0
  keyboard_actions: ^4.2.0

  firebase_messaging: ^16.0.0
  firebase_database: ^12.0.0
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0

  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.12
  connectivity_plus: ^6.1.4
  uuid: ^4.5.1
  fl_chart: ^0.66.0
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/logo/
    - assets/images/slides/

  fonts:
    - family: InterRegular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

    - family: InterSemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf

    - family: InterBold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf

    - family: InterMedium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf